KoalaSat/pokey

app/build.gradle.kts
=> v0.0.1-alpha

app/build.gradle.kts
=> v0.0.2-alpha

zapstore.yaml
=> Fixes Zap store

app/src/main/java/com/koalasat/pokey/MainActivity.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeViewModel.kt, app/src/main/res/drawable/ic_amber.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/strings.xml
=> amber button

app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeViewModel.kt, app/src/main/res/values/strings.xml
Open notification to external uri client
=> Open notification to external uri client

app/build.gradle.kts
=> v0.0.3-alpha

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/res/layout/fragment_home.xml
=> Zaps display to int

app/src/main/java/com/koalasat/pokey/MainActivity.kt, app/src/main/java/com/koalasat/pokey/Pokey.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt
=> NIP-42 Auth to Relays

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
- Adds events queue atomic checks to avoid duplication
- Fix relays recovery on startup
- Better notification priorities
=> Fix channel recovery and add events queue

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Broadcast events

app/build.gradle.kts
=> v0.0.4-alpha

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Better zaps

app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/notifications/NotificationsFragment.kt, app/src/main/java/com/koalasat/pokey/ui/notifications/NotificationsViewModel.kt, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/values/strings.xml
=> Disable events broadcasting

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Wait to connect to relays

app/build.gradle.kts
=> v0.0.5-alpha

app/src/main/java/com/koalasat/pokey/ui/relays/RelaysFragment.kt
Confirm add relay with big list
=> Confirm add relay with big list

app/src/main/java/com/koalasat/pokey/ui/relays/RelaysFragment.kt, app/src/main/res/values/strings.xml
Fixes #<ISSUE_NUMBER>
This PR introduces/refactors/...
=> Translations

app/src/main/AndroidManifest.xml, app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
- Fix Content resolver not working
- Fix relay auth
=> Fix relay auth and content resolver

app/src/main/AndroidManifest.xml, app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Revert "Fix relay auth and content resolver"

app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/relays/RelaysFragment.kt, app/src/main/res/drawable/ic_remove_red_24dp.xml
=> Better relay auth

app/src/main/java/com/koalasat/pokey/ui/relays/RelaysFragment.kt, app/src/main/res/layout/fragment_relays.xml
=> Publish relay lists

app/build.gradle.kts
=> v0.0.6-alpha

app/src/main/java/com/koalasat/pokey/ui/relays/RelayListAdapter.kt, app/src/main/java/com/koalasat/pokey/utils/ThemeUtils.kt
=> Fix relay list text color when in light theme

app/src/main/AndroidManifest.xml, app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt
=> Fix Content resolver not working

app/build.gradle.kts
=> v0.0.7-alpha

.github/workflows/create-release.yml, .idea/misc.xml, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Fix infinite loop on auth

app/build.gradle.kts
=> v0.0.8-alpha

app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/BootReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> display nip05

app/src/main/java/com/koalasat/pokey/MainActivity.kt, app/src/main/java/com/koalasat/pokey/service/BootReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Fix app recovery on boot

app/build.gradle.kts
=> v0.0.9-alpha

.idea/misc.xml, app/schemas/com.koalasat.pokey.database.AppDatabase/6.json, app/src/main/AndroidManifest.xml, app/src/main/java/com/koalasat/pokey/database/AppDatabase.kt, app/src/main/java/com/koalasat/pokey/database/ApplicationDao.kt, app/src/main/java/com/koalasat/pokey/database/MuteEntity.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/NotificationReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/res/values/strings.xml
=> Add mute thread button

app/build.gradle.kts
=> v0.1.0-alpha

app/schemas/com.koalasat.pokey.database.AppDatabase/8.json, app/src/main/java/com/koalasat/pokey/Pokey.kt, app/src/main/java/com/koalasat/pokey/database/AppDatabase.kt, app/src/main/java/com/koalasat/pokey/database/ApplicationDao.kt, app/src/main/java/com/koalasat/pokey/database/UserEntity.kt, app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/BootReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationFragment.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationViewModel.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeViewModel.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/values/strings.xml
=> Move user to db

app/build.gradle.kts
=> v0.1.1-alpha

app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationFragment.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationViewModel.kt
=> Fix refresh config

.github/workflows/build.yml, .github/workflows/create-release.yml, app/build.gradle.kts, build.sh
=> Generate other archs

app/build.gradle.kts, app/schemas/com.koalasat.pokey.database.AppDatabase/9.json, app/src/main/java/com/koalasat/pokey/Pokey.kt, app/src/main/java/com/koalasat/pokey/database/AppDatabase.kt, app/src/main/java/com/koalasat/pokey/database/ApplicationDao.kt, app/src/main/java/com/koalasat/pokey/database/MuteEntity.kt, app/src/main/java/com/koalasat/pokey/database/RelayEntity.kt, app/src/main/java/com/koalasat/pokey/database/UserEntity.kt, app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/NotificationReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationFragment.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationViewModel.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeViewModel.kt, app/src/main/java/com/koalasat/pokey/ui/relays/RelayListAdapter.kt, app/src/main/java/com/koalasat/pokey/ui/relays/RelaysFragment.kt, app/src/main/java/com/koalasat/pokey/ui/relays/RelaysViewModel.kt, app/src/main/res/drawable/ic_add_circle_24dp.xml, app/src/main/res/layout/fragment_add_account.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/layout/fragment_primary_account.xml, app/src/main/res/layout/fragment_relays.xml, app/src/main/res/menu/user_popup_menu.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, gradle/libs.versions.toml
=> Multiaccount

app/src/main/java/com/koalasat/pokey/service/BootReceiver.kt
=> Check internet boot on start

app/build.gradle.kts
=> v0.1.2-alpha

app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt
=> Fix start button

app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/ui/home/HomeFragment.kt, app/src/main/res/values/strings.xml
=> Fix Amber sync

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
=> Recover background service

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt
Fix crash when inserting the notification into the database
=> Fix crash when inserting the notification into the database

.github/workflows/build.yml, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/res/values/strings.xml
Displays number of connected relays on the permanent notification
=> Show connected relays

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, gradle/libs.versions.toml
=> Display Zapper profile

app/src/main/java/com/koalasat/pokey/models/EncryptedStorage.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationFragment.kt, app/src/main/java/com/koalasat/pokey/ui/configuration/ConfigurationViewModel.kt, app/src/main/res/layout/fragment_configuration.xml, app/src/main/res/values/strings.xml
=> Limit tagged users

app/build.gradle.kts
=> v0.1.5-alpha

app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, zapstore.yaml
=> Include mentions

app/build.gradle.kts
=> v0.1.6-alpha

app/build.gradle.kts
=> v0.2.0-beta

app/src/main/java/com/koalasat/pokey/MainActivity.kt, app/src/main/java/com/koalasat/pokey/database/ApplicationDao.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/NotificationReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/res/menu/menu_main.xml, app/src/main/res/values/strings.xml
=> Manage private mute list

app/src/main/java/com/koalasat/pokey/MainActivity.kt, app/src/main/java/com/koalasat/pokey/Pokey.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/res/values/strings.xml
Manually update mute list with notification
=> Manually update mute list with notification

app/schemas/com.koalasat.pokey.database.AppDatabase/11.json, app/src/main/java/com/koalasat/pokey/MainActivity.kt, app/src/main/java/com/koalasat/pokey/database/AppDatabase.kt, app/src/main/java/com/koalasat/pokey/database/ApplicationDao.kt, app/src/main/java/com/koalasat/pokey/database/MuteEntity.kt, app/src/main/java/com/koalasat/pokey/database/NotificationEntity.kt, app/src/main/java/com/koalasat/pokey/models/ExternalSigner.kt, app/src/main/java/com/koalasat/pokey/models/NostrClient.kt, app/src/main/java/com/koalasat/pokey/service/NotificationReceiver.kt, app/src/main/java/com/koalasat/pokey/service/NotificationsService.kt, app/src/main/java/com/koalasat/pokey/ui/notifications/NotificationsFragment.kt, app/src/main/res/values/strings.xml
=> Mute action

app/build.gradle.kts, release_notes.md
=> v0.2.4-beta
